### ISSUE TITLE
Checklist for finalizing Approved SOAP-Attachments 3.0

### ISSUE THREAD

**Issue by edbratt** [eclipse-ee4j/saaj-api#126]
This checklist will help you complete all the final actions necessary for finishing up the recently approved SOAP-Attachments Specification Release:
 - [ ] promote api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
 - [ ] go through the merged jakarta.ee specification website page to verify all the links are valid.
 - [ ] if XML Schemas are published on https://jakarta.ee/schemas, send a PR to update the status from `Draft` to `Final`.
 - [ ] approve the compatibility request issue
 - [ ] The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
 - [ ] merge any final release branch as appropriate for the branch management for the project.

I've assigned this to the project lead, but any committer with the requisite knowledge may take these actions and check off the items listed above. 

Thank you for your work and dedication to Jakarta EE!

**Comment by edbratt** [comment]
Please also remember to update the final check-list item (11) of the [Specification PR](https://github.com/jakartaee/specifications/pull/444#issuecomment-1034028458) -- which reminds you to update the Jakarta EE API JAR.
